# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:8.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: build
  deploy:
    docker:
      - image: 'circleci/python:2.7'
    working_directory: ~/repo
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - aws-s3/sync:
          from: build
          to: 's3://karanverma.me'
          arguments: |
            --acl public-read \
            --cache-control "max-age=31557600" \
            --content-encoding "gzip"
          overwrite: true
      # This is a work around for uploading index,html in not gzipped form
      - aws-s3/sync:
          from: build/index.html
          to: 's3://karanverma.me'
          arguments: |
            --acl public-read \
            --cache-control "max-age=31557600" \
          overwrite: true

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master